<script lang="ts">
    import { math } from 'mathlifier';
	import Hoverable from '$lib/components/Hoverable.svelte';
    import wikiSummaryBit from './wiki/wikiSummaryBit.html?raw';
    import wikiSummaryQubit from './wiki/wikiSummaryQubit.html?raw';
    import wikiSummaryComplex_number from './wiki/wikiSummaryComplex_number.html?raw';


    function setActive(e){
        console.log(e)
    }

</script>

<h2>Qubit states</h2>
<p>The elementary units of information in classical computing are <Hoverable hovertext={wikiSummaryBit}>bits</Hoverable>. As their name suggests, bits represent one single <em>bit</em> of information, which means they can take on either of two values <span on:mouseenter={() => setActive([])}>{@html math("0")}</span> and <span on:mouseenter={() => setActive([])}>{@html math("1")}</span> at a time.</p>
<p><Hoverable hovertext={wikiSummaryQubit}>Qubits</Hoverable> are the quantum computing equivalent of bits. They differ from classical bits - among other things - in that they can take on a multitude of values instead of just <span on:mouseenter={() => setActive([])}>{@html math("0")}</span> and <span on:mouseenter={() => setActive([])}>{@html math("1")}</span>, until that value is <em>measured</em>, at which point they behave just like classical bits. To explain what this means exactly, we'll need to introduce some further concepts.</p>
<p>Let <span on:mouseenter={() => setActive([])}>{@html math("|0\\rangle")}</span> and <span on:mouseenter={() => setActive([])}>{@html math("|1\\rangle")}</span> denote the so called <em>basis states</em> of a qubit that are the quantum-equivalent of classical bit states. If you look at a qubit directly to learn it's value, you'll see one of these basis states. But while you're not looking - due to it's quantum nature - the state of a qubit may be something more intricate. Generally, it can be expressed as the <em>linear combination</em> of the two basis states: <span on:mouseenter={() => setActive(["\\alpha", "\\beta"])}>{@html math("\\alpha |0\\rangle + \\beta |1\\rangle")}</span>. Here, <span on:mouseenter={() => setActive(["\\alpha"])}>{@html math("\\alpha")}</span> and <span on:mouseenter={() => setActive(["\\beta"])}>{@html math("\\beta")}</span> are <Hoverable hovertext={wikiSummaryComplex_number}>complex numbers</Hoverable> that indicate the relative weight, with which the two basis states are present in this combination. More precisely, if we now look at the qubit, we'll see the basis state <span on:mouseenter={() => setActive([])}>{@html math("|0\\rangle")}</span> with a probability of <span on:mouseenter={() => setActive(["\\alpha"])}>{@html math("\\Vert{\\alpha}\\Vert^2")}</span>, and the basis state <span on:mouseenter={() => setActive([])}>{@html math("|1\\rangle")}</span> with a probability of <span on:mouseenter={() => setActive(["\\beta"])}>{@html math("\\Vert{\\beta}\\Vert^2")}</span>. Because these probabilities must add up to one - as <span on:mouseenter={() => setActive([])}>{@html math("|0\\rangle")}</span> and <span on:mouseenter={() => setActive([])}>{@html math("|1\\rangle")}</span> are the only possible outcomes - the equation <span on:mouseenter={() => setActive(["\\alpha", "\\beta"])}>{@html math("\\Vert{\\alpha}\\Vert^2 + \\Vert{\\beta}\\Vert^2 = 1")}</span> must hold for all possible qubit states. Let's call <span on:mouseenter={() => setActive(["\\alpha"])}>{@html math("\\Vert{\\alpha}\\Vert^2")}</span> and <span on:mouseenter={() => setActive(["\\beta"])}>{@html math("\\Vert{\\beta}\\Vert^2")}</span> the <em>measurement probabilities</em> of the basis states.</p>
<!-- TODO introduce the interactivity -->