<script lang="ts">
    import { math } from 'mathlifier';
	import Hoverable from '$lib/components/Hoverable.svelte';
    


    function setActive(e){
        console.log(e)
    }

</script>

<h2>The Bloch-sphere</h2>
<p>As the coefficients <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\alpha")}</span> and <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\beta")}</span> are complex numbers, they can be expressed in the form <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\alpha = \\Vert{\\alpha}\\Vert \\cdot e^{i \\phi_{\\alpha}}")}</span> and <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\beta = \\Vert{\\beta}\\Vert \\cdot e^{i \\phi_{\\beta}}")}</span>. Thus, the state of the qubit can be rewritten as <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\Vert{\\alpha}\\Vert \\cdot e^{i \\phi_{\\alpha}} |0\\rangle + \\Vert{\\beta}\\Vert \\cdot e^{i \\phi_{\\beta}} |1\\rangle")}</span>.</p>
<p>Remember that <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("e^{i \\phi_{\\alpha}}")}</span> is a unit vector rotated around the origin, and therefore the square of its norm <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\Vert{e^{i \\phi_{\\alpha}}}\\Vert^2")}</span> also equals to <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("1")}</span>. This means that we can modify the angles <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\phi_{\\alpha}")}</span> and <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\phi_{\\beta}")}</span> freely without affecting the measurement probabilities. Therefore, we can do an algebraic trick to simplify the expression above. Namely, let's divide the state by <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("e^{i \\phi_{\\alpha}}")}</span> to obtain <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\Vert{\\alpha}\\Vert \\cdot |0\\rangle + \\Vert{\\beta}\\Vert \\cdot \\frac{e^{i \\phi_{\\beta}}}{e^{i \\phi_{\\alpha}}} |1\\rangle")}</span>. By the rules of exponentiation, <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\frac{e^{i \\phi_{\\beta}}}{e^{i \\phi_{\\alpha}}} = e^{i (\\phi_{\\beta} - \\phi_{\\alpha})}")}</span>. Next, let's introduce a new variable <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\phi = \\phi_{\\beta} - \\phi_{\\alpha}")}</span>, with the help of which the state can be further simplified to <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\Vert{\\alpha}\\Vert \\cdot |0\\rangle + \\Vert{\\beta}\\Vert \\cdot e^{i \\phi} |1\\rangle")}</span>.</p>
<p>We know that <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\Vert{\\alpha}\\Vert^2 + \\Vert{\\beta}\\Vert^2 = 1")}</span>. Consequently, these two numbers can also be represented geometrically as vector of unit length rotated around the origin by some angle, the <em>double</em> of which we'll denote as <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\theta")}</span>. Using trigonometry, we can now rewrite the state as <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\cos{(\\frac{\\theta}{2})} \\cdot |0 \\rangle + \\sin{(\\frac{\\theta}{2})} \\cdot e^{i \\phi} |1 \\rangle")}</span>. Notice, that we now only need two variables to express the state of the qubit: the angles <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\theta")}</span> and <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\phi")}</span>. Geometrically, this can be represented as a vector pointing to the surface of 3-dimensional sphere with unit radius, where <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\theta")}</span> is the angle of the vector and the <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("z")}</span> axis, and <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\phi")}</span> is the angle of the vertical projection of the vector on the <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("x-y")}</span> plane. This representation of qubit states is called the <em>Bloch sphere</em>.</p>
<p>It's important to note that of the two degrees of freedom on the Bloch sphere, only the angle <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\theta")}</span> is related to measurement probabilities. <span on:mouseenter={() => setActive(["a", "b"])}>{@html math("\\phi")}</span> is an inherently quantum property called the <em>phase</em> that does not have physical manifestation directly observable to us. Because of this, it's hard to find any intuitive analogy from everyday life that could help us understand what exactly the phase is. The most useful approach in this context is to look at the phase as a matematical property of quantum objects that we can leverage to design clever algorithms.</p>
<h1>TODO</h1>
<blockquote>
<p>make sure the connection is made between the representation and playing with the bloch sphere is possible</p>
</blockquote>